services:
  bot:
    container_name: bot
    image: theoguerin/my_discord_bot
    build: .
    env_file:
      - ./.env
    networks:
      - internal
    logging:
      driver: local
    restart: unless-stopped
networks:
  internal:
    driver: bridge
