services:
  bot:
    image: theoguerin/my_discord_bot
    build:
      context: .
      target: dev
    env_file:
      - ./.env
    networks:
      - internal
    logging:
      driver: local
    restart: unless-stopped
networks:
  internal:
    driver: bridge
